### ISSUE TITLE
Missing translations for Datepicker and weird dates in backend

### ISSUE THREAD

**Issue by rbarisic-lme** [spree/spree#10752]
![image](https://user-images.githubusercontent.com/54026388/106667642-77e05100-65a9-11eb-9790-e4a615dabb93.png)

I'm using the spree-starter from the guides with bin/setup. I'm getting this error

**Comment by MatthewKennedy** [comment]
Hi @rbarisic-lme 

in your language file you will ned to add the date formatting.
https://github.com/spree/spree/blob/2faae96b92b8604eadd6d790b49d96c0e8e79f0f/core/config/locales/en.yml#L761

```yml
spree:
    date_picker:
      am: 'AM'
      first_day: 0
      format: ! '%Y/%m/%d'
      hourAriaLabel: 'Hour'
      js_format: Y/m/d
      js_date_time: Y/m/d - H:i
      minuteAriaLabel: 'Minute'
      pm: 'PM'
      rangeSeparator: ' to '
      scrollTitle: 'Scroll to increment'
      toggleTitle: 'Click to toggle'
      weekAbbreviation: 'Wk'
      yearAriaLabel: 'Year'
      sun: 'Sun'
      mon: 'Mon'
      tue: 'Tue'
      wed: 'Wed'
      thu: 'Thu'
      fri: 'Fri'
      sat: 'Sat'
      lh_jan: 'January'
      lh_feb: 'February'
      lh_mar: 'March'
      lh_apr: 'April'
      lh_may: 'May'
      lh_jun: 'June'
      lh_jul: 'July'
      lh_aug: 'August'
      lh_sep: 'September'
      lh_oct: 'October'
      lh_nov: 'November'
      lh_dec: 'December'
```
