### ISSUE TITLE
Emailed order confirmation design issue on <=600px screen (3-0-stable)

### ISSUE THREAD

**Issue by devsli** [spree/spree#6593]
# Steps to reproduce

1. Make an order
1. Open order confirmation email in iPhone mail / Thunderbird / [MailCatcher](https://github.com/sj26/mailcatcher)
1. Resize it to 50—600px width

## 600px email

First column is stretched:
![CSS responsive column fail](http://i.imgur.com/fLY3Kis.png)

## 601px email
![601px width seems not so bad](http://i.imgur.com/Rxz5DFi.png)

# Suspicious CSS

[base_mailer.html.erb](https://github.com/spree/spree/blob/master/core/app/views/layouts/spree/base_mailer.html.erb)
```css
@media only screen and (max-width: 600px) {
  /*\
   *
  \*/

  table[class="body"] table.columns td,
  table[class="body"] table.column td {
    width: 100% !important;
  }

  /*\
   *
  \*/
}
```
