### ISSUE TITLE
Path helpers not respecting Spree mountpoint in tests

### ISSUE THREAD

**Issue by kimadactyl** [spree/spree#6753]
I'm trying to write some integration tests in Minitest to test my checkout flow. It seems like Spree isn't respecting my mountpoint. I'm getting the error ```ActionController::RoutingError: No route matches [GET] "/products/tai-chi-foundation"``` wheras it should be ```"/shop/products/tai-chi-foundation"``` as I have ```mount Spree::Core::Engine, :at => '/shop'``` in ```routes.rb```.

I think this is all the relevant files?

Thanks!

```bash
kim@chips:~/taichi/taichi_rails$ rake test test/integration/spree/order_test.rb 
Started with run options --seed 63455

ERROR["test_checkout_flow", OrderTest, 2015-09-23 11:00:34 +0100]
 test_checkout_flow#OrderTest (1443002434.47s)
ActionController::RoutingError:         ActionController::RoutingError: No route matches [GET] "/products/tai-chi-foundation"
            test/integration/spree/order_test.rb:11:in `block in <class:OrderTest>'

  1/1: [=============================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.28624s
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips

```

```ruby
# test/integration/spree/order_test.rb
require 'test_helper'

class OrderTest < ActionDispatch::IntegrationTest
  def setup
    @user = users(:kim)
    @product = spree_products(:foundation)
  end

  test "checkout flow" do
    # Helper method in my app, I'm using my own authentication
    log_in_as(@user)
    # Next line returns the error
    get spree.product_path(@product), "Tai Chi Foundation product doesn't exist"
  end
end
```

```yml
# test/fixtures/spree/products.yml
foundation:
  id: 1
  name: "Tai Chi Foundation"
  description: ""
  available_on: "2015-09-13 00:00:00"
  deleted_at: nil
  slug: "tai-chi-foundation"
  meta_description: ""
  meta_keywords: ""
  tax_category_id: 2
  shipping_category_id: 1
  created_at: "2015-09-21 14:55:09"
  updated_at: "2015-09-21 15:58:08"
  promotionable: true
  meta_title: nil


```
