### ISSUE TITLE
i18n - plurals translation

### ISSUE THREAD

**Issue by bonekost** [spree/spree#7709]
I try to make more plurals for order form. (other language than `:en` got more plurals).

I got this:

    #config/initializers/pluralization.rb
    
    require "i18n/backend/pluralization"
    I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)
 and

    #config/locales/plurals.rb
    {:cs => 
      { :i18n => 
        { :plural => 
          { :keys => [:one, :few, :other], 
            :rule => lambda { |n| n == 1 ? :one : [2, 3, 4].include?(n) ? :few : :other } 
          } 
        } 
      },
    }
and

    #config/locales/cs.yml
    cs:
      spree:
        cart_subtotal:
          one: 'loremimpsum (1 prdukt)'
          few: 'loremimpsum (%{count} produkty)'
          other: 'loremimpsum (%{count} produktu)'
and

    #orders/_form.html.erb
    <%= Spree.t('cart_subtotal', count: @order.line_items.sum(:quantity)) %>

but it doesn't work.

**Comment by priyank-gupta** [comment]
@bonekost You are missing few things here.
```
#config/locales/cs.yml
cs:
  spree:
    cart_subtotal:
      one: 'loremimpsum (1 prdukt)'
      few: 'loremimpsum (%{count} produkty)'
      other: 'loremimpsum (%{count} produktu)'
```
And
```
#orders/_form.html.erb
<%= Spree.t('cart_subtotal', count: @order.line_items.sum(:quantity), locale: :cs) %>
```
