### ISSUE TITLE
Spree locales can not be changed in development

### ISSUE THREAD

**Issue by arkirchner** [spree/spree#8783]
I am running rails 5.2 with spree 3.6.0.rc1.

I want to override some of sprees I18n keys. I am Placing this in my `config/locales/en.yml`

```
en:
  spree:                                                                                                                                                                                                     
    cart_subtotal:                                                                                                                                                                                           
      one: "FooBar %{count} "                                                                                                                                                                                  
      other: "BarFoo %{count} d"
```

In my application this happens. The translations keys are applied in testing and production. In development I see only default provided by spree.

If I change `cache_classes` in my `config/environments/development.rb` I can see it (But this makes development impossible). 
```
  config.cache_classes = true
```

I tried to reproduce this with a vanilla rails 5.2 and I can see the custom keys I created. However when I update the keys it falls back to showing only the spree defaults.

I created a second sample app with thoughtbots suspenders gem and the behaviour is the same as in my application. In development I can not override the localization keys.

## Context
<!--- Provide a more detailed introduction to the issue itself -->
<!--- How has this issue affected you? What were you trying to accomplish? -->

## Expected Behavior
I18n keys can be overridden and changed in the `config/locales/en.yml` in development mode.

## Actual Behavior
When `config/locales/en.yml` is changed overrides are ignored and spree defaults are shown.

## Steps to Reproduce
1. Create a new rails 5.2.0 app.
2. Install spree in version 3.6.0.rc1.
3. Start the spree app and add a item to the cart site. Checkout and add an address and go back to see "Subtotal (2 items)". 
4.  Add this locales to "config/locales/en.ym"
```
en:
  spree:                                                                                                                                                                                                     
    cart_subtotal:                                                                                                                                                                                           
      one: "FooBar %{count} "                                                                                                                                                                                  
      other: "BarFoo %{count} d"
```
Reload the page and see that nothing changed.
5. Restart the rails app and you can see your custom update.
6. Chane your custom keys again and the spree default will be displayed.

## Your Environment
My Gemfile off the vanilla rails app:
https://gist.github.com/arkirchner/377aa8a1737be20c0cb6ba5db96b3783

Any help would very welcome m(_ _)m
