### ISSUE TITLE
Spree model fixture fails to load with an association defined by a decorator

### ISSUE THREAD

**Issue by thomasnal** [spree/spree#8785]
## Context

Assume `Spree::Product` decorated by a `supplier` association, 
```ruby
# app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  belongs_to :supplier
end
```
with `supplier_id` added to `spree_products`,
```ruby
class AddSupplierIdToSpreeProduct < ActiveRecord::Migration[5.2]
  def change
    add_column :spree_products, :supplier_id, :integer
    add_index :spree_products, :supplier_id
  end
end
```
```sh
bin/rails db:migrate:status
...
   up     20180414112953  Add supplier id to spree product
...
```
And assume a supplier fixture `tshirt_supplier`,
```yaml
# test/fixtures/suppliers.yml
tshirt_supplier:
  name: tshirt_supplier
```
Then assign the supplier to  spree product fixture `tshirt`,
```yaml
# test/fixtures/spree_products.yml
tshirt:
  supplier: tshirt_supplier
```

## Expected Behavior
Spree product fixture `tshirt` will load with value of `supplier` association set to `tshirt_supplier` fixture.

## Actual Behavior
Rails tests fail to start with error:
```sh
bin/rails test test/models/supplier.rb
```
```ruby
ActiveRecord::Fixture::FixtureError: table "spree_products" has no columns named "supplier".
```

## Your Environment
* Version used: spree-3.5

**Comment by arkirchner** [comment]
@thomasnal 
This is a problem with the fixtures you are using. It is not  possible to assign associations like this. You could do this:
```
# test/fixtures/suppliers.yml
tshirt_supplier:
  id: 1
  name: tshirt_supplier
```

```
  # test/fixtures/spree_products.yml
  tshirt:
    supplier_id: 1
```

However I do not recommend to define the IDs like this. Maybe you want to switch to a different way of creating your fixtures for testing. Spree uses "Factory Bot" to create models for testing. It has support for associations.

https://github.com/thoughtbot/factory_bot_rails
